import "@styles/globals.css";
import type { AppProps } from "next/app";
import { useEffect, useState } from "react";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import "@rainbow-me/rainbowkit/styles.css";
import {
  getDefaultWallets,
  RainbowKitProvider,
  Theme,
  darkTheme,
} from "@rainbow-me/rainbowkit";
import { publicProvider } from "wagmi/providers/public";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import merge from "lodash.merge";
import { Chain } from "wagmi/chains";
import Head from "next/head";

const thetaTestnet: Chain = {
  id: 365,
  name: "Theta Testnet",
  network: "TFUEL",
  nativeCurrency: {
    decimals: 18,
    name: "TFUEL",
    symbol: "TFUEL",
  },
  rpcUrls: {
    default: {
      http: ["https://eth-rpc-api-testnet.thetatoken.org/rpc"],
    },
    public: {
      http: ["https://eth-rpc-api-testnet.thetatoken.org/rpc"],
    },
  },
  blockExplorers: {
    default: { name: "Explorer", url: "https://beta-explorer.thetatoken.org/" },
  },
  testnet: true,
};

const { chains, publicClient } = configureChains(
  [thetaTestnet],
  [publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: "Nexus",
  projectId: "3c045efb77d80d389713970296b69d81",
  chains,
});

const wagmiClient = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
});

/* Theming */
const theme = extendTheme({
  styles: {
    global: {
      "*": {
        fontFamily: "Montserrat",
      },
      a: {
        _hover: {
          textDecoration: "underline",
        },
      },
    },
  },
});

const projectId = "3c045efb77d80d389713970296b69d81";

const customTheme = merge(darkTheme(), {
  colors: {
    accentColor: "#FFFFFF",
  },
} as Theme);

function MyApp({ Component, pageProps, router }: AppProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <WagmiConfig config={wagmiClient}>
      <RainbowKitProvider chains={chains} theme={customTheme}>
        <ChakraProvider theme={theme}>
          <Head>
            <title>Nexus: Metaverse Marketplace</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} key={router.route} />
          {/* <Web3Modal projectId={projectId} ethereumClient={ethereumClient} /> */}
        </ChakraProvider>
      </RainbowKitProvider>
    </WagmiConfig>
  );
}

export default MyApp;
