import "@styles/globals.css";
import type { AppProps } from "next/app";
import { useEffect, useState } from "react";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import { publicProvider } from "wagmi/providers/public";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { polygonZkEvmTestnet } from "wagmi/chains";
import Head from "next/head";
import { InjectedConnector } from "wagmi/connectors/injected";
import { AuthProvider } from "@components/AuthProvider";

const { chains, provider } = configureChains(
  [polygonZkEvmTestnet],
  [publicProvider()]
);

const wagmiClient = createClient({
  autoConnect: true,
  connectors: [new InjectedConnector({ chains })],
  provider,
});

/* Theming */
const theme = extendTheme({
  styles: {
    global: {
      "*": {
        fontFamily: "Montserrat",
      },
      a: {
        _hover: {
          textDecoration: "underline",
        },
      },
    },
  },
});

function MyApp({ Component, pageProps, router }: AppProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <WagmiConfig client={wagmiClient}>
      <ChakraProvider theme={theme}>
        <AuthProvider>
          <Head>
            <title>Playz: Unleash your creative capital</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} key={router.route} />
        </AuthProvider>
      </ChakraProvider>
    </WagmiConfig>
  );
}

export default MyApp;
